#  ── .streamlit/secrets.toml  ─────────────────────────
#  These are placeholders so Streamlit stops crashing.
#  They are NOT used now that we speak with Edge-TTS.

aws_access_key_id     = ""
aws_secret_access_key = ""
aws_region            = "us-east-1"
